version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: databeez-postgres
    environment:
      POSTGRES_DB: databeez
      POSTGRES_USER: databeez
      POSTGRES_PASSWORD: databeez123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - databeez-network

  redis:
    image: redis:7-alpine
    container_name: databeez-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - databeez-network

  # Service optionnel pour visualiser la base de données
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: databeez-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@databeez.africa
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - databeez-network

volumes:
  postgres_data:
  redis_data:

networks:
  databeez-network:
    driver: bridge 